'use strict';

// spirit/test/publishCapacity.js
// THE FRONT PAGE'S CAPACITY CLAIM, WRITTEN BY THE MEASUREMENT.
//
//   Andy, 2026-09-23: "the front page README.md should have a marked block
//   that will be auto-updated with the ubuntu-relay capacity only, the rest
//   of the auto-generated capacity branch of the README/ tree can be pushed
//   as is" — and, on why any of this exists: "core improvements WILL move
//   the numbers we document in the README tree of the repo."
//
//   node spirit/test/publishCapacity.js          rewrite the block
//   node spirit/test/publishCapacity.js --check   exit 1 if it is out of date
//
// ── UBUNTU ONLY, AND THAT IS THE WHOLE POINT ─────────────────────────
//
// Andy, the same day: *"swl harness is the target for relay, windows may
// be the prime target for node."* The front page makes ONE claim, about
// the box a relay actually runs on. A Windows run must never touch it —
// not because the Windows figures are worse, but because a front page
// that silently shows whichever platform measured last is a front page
// nobody can cite.
//
// The per-platform detail is not summarised here and is not meant to be.
// It is generated whole by `measurePlatform.js --save` and committed as
// it stands; this block links to it.
//
// ── IT PUBLISHES THE MEASUREMENT'S AGE, NOT JUST ITS NUMBERS ─────────
//
// Every figure carries the commit and date it was taken at. A generated
// block can be stale exactly as a typed one can — `capacityFresh.js`
// caught the 197 that sat on this page for two days — and the difference
// between the two is that this one says how old it is without being
// asked. A reader who can see "measured at 27374ee, 2026-09-21" can
// weigh the number; a reader looking at a bare "197 bytes" cannot.

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..', '..');
const PAGE = path.join(ROOT, 'README.md');
// ── WHICH UBUNTU, AND WHY IT IS NOT NAMED HERE ───────────────────────
//
//   Andy, 2026-09-23: "the index to platforms may have to be updated when
//   i have my pure-ubuntu box live again."
//
// So the slug is CHOSEN, not written down. A bare-metal Ubuntu measurement
// wins over a WSL one the moment it exists, with no edit here and no
// release note — because the day that box comes up is the day this page
// should stop quoting a virtual machine, and nobody will remember to come
// and change a constant.
//
// WSL IS A PROXY AND THE BLOCK SAYS SO. Same distribution, same libc, same
// Node — but a VM on a 64 GB workstation, not a 1 GB VPS under memory
// pressure. It is the best Ubuntu figure available until it is not, and a
// reader deserves to know which one they are looking at.
function pickUbuntu() {
  const dir = path.join(ROOT, 'README', 'CAPACITY');
  let names = [];
  try {
    names = fs.readdirSync(dir).filter(function (nm) {
      return /^ubuntu/i.test(nm) && fs.existsSync(path.join(dir, nm, 'capacity.json'));
    }).sort();
  } catch (e) { names = []; }
  const bare = names.filter(function (nm) { return !/wsl/i.test(nm); });
  return (bare.length ? bare : names)[0] || '';
}

const PLATFORM = pickUbuntu();
const SOURCE = PLATFORM
  ? path.join(ROOT, 'README', 'CAPACITY', PLATFORM, 'capacity.json')
  : '';

const OPEN = '<!-- capacity:ubuntu-relay:start — generated by spirit/test/publishCapacity.js; do not edit by hand -->';
const SHUT = '<!-- capacity:ubuntu-relay:end -->';

function mb(bytes) { return (Number(bytes || 0) / 1048576).toFixed(1); }
function n(x) { return Number(x || 0).toLocaleString('en-US'); }

// How many may be CONNECTED at a given relay RAM limit. The relay's own
// allowance is 16 a megabyte (relay.js), and the measured cost is what
// says whether that allowance is honest on this platform — so both are
// printed and a reader can see which one binds.
function connected(limitMB, perStream) {
  if (!perStream) return '—';
  return n(Math.floor((limitMB * 1048576) / perStream));
}

function render(c) {
  const per = Number(c.perStreamProcessBytes || 0);
  const carded = Number(c.perMemberRowBytes || 0);
  const plain = Number(c.perMemberRowBytesUncarded || 0);
  const gig = 1073741824;

  const lines = [];
  lines.push(OPEN);
  lines.push('');
  lines.push('### An Ubuntu relay, measured');
  lines.push('');
  lines.push('Taken on `' + PLATFORM + '` at commit `' +
    String(c.commit || '?').slice(0, 7) + '`, ' + String(c.measuredAt || '?').slice(0, 10) +
    '. Ubuntu because **that is what a relay runs on** — the Windows figures ' +
    'are measured too and kept beside these, never averaged with them.' +
    (/wsl/i.test(PLATFORM)
      ? ' **This is WSL, which is a proxy**: the same distribution and the ' +
        'same runtime, but a virtual machine on a workstation rather than a ' +
        'small VPS under memory pressure. Bare-metal figures replace these ' +
        'automatically once such a box publishes.'
      : ''));
  lines.push('');
  lines.push('| | |');
  lines.push('|---|---|');
  lines.push('| at rest | **' + mb(c.relayAtRestRss) + ' MB** resident |');
  lines.push('| a held connection | **' + n(per) + ' bytes** |');
  // ── THE LABEL IS ONLY WRITTEN WHEN IT IS KNOWN TO BE TRUE ──────────
  //
  // `perMemberRowBytesUncarded` exists only in measurements taken by the
  // tool AFTER it learned to write a card on the row. Its ABSENCE means
  // this drop predates cycle 10, and `perMemberRowBytes` there is a
  // cardless member — so calling it "with their card" would publish a
  // false sentence over a true number.
  //
  // Caught by reading the generated output, 2026-09-23, which had already
  // rendered "197 bytes with their card" once. The third instance that day
  // of the same failure: a machine-written figure is not a checked one,
  // and automation propagates a wrong question faster than a person does.
  if (plain) {
    lines.push('| a member on disc | **' + n(carded) + ' bytes** with their card, ' +
      n(plain) + ' without |');
  } else {
    lines.push('| a member on disc | **' + n(carded) + ' bytes** — measured ' +
      'BEFORE the signed card was added to the row, so this understates a ' +
      'member today |');
  }
  if (c.cardBytes) lines.push('| the card itself | ' + n(c.cardBytes) + ' bytes, signed |');
  lines.push('');
  lines.push('| relay RAM limit | connected at once |');
  lines.push('|---|---|');
  [128, 256, 512].forEach(function (limit) {
    lines.push('| ' + limit + ' MB | **' + connected(limit, per) + '** |');
  });
  lines.push('');
  // Derived from the CARDED figure only. Dividing a gigabyte by a
  // cardless row prints a roll three times larger than the one a relay
  // would actually hold, which is the most quotable number on the page.
  if (carded && plain) {
    lines.push('A **1 GB disc** holds **' + n(Math.floor(gig / carded)) +
      '** members. A relay is bounded by RAM, not by its roll — and the gap ' +
      'between those two numbers is the design.');
    lines.push('');
  } else if (carded) {
    lines.push('**The roll figure is withheld until this box re-measures.** ' +
      'A gigabyte divided by a pre-card row would print a membership ' +
      'roughly three times larger than a relay could hold — and that is ' +
      'the most quotable number on this page.');
    lines.push('');
  }
  lines.push('Every figure, both platforms, and the command to re-measure: ' +
    '[README/CAPACITY/](README/CAPACITY/).');
  lines.push('');
  lines.push(SHUT);
  return lines.join('\n');
}

function main() {
  let c = null;
  try { c = JSON.parse(fs.readFileSync(SOURCE, 'utf8')); }
  catch (e) {
    console.log('no Ubuntu measurement to publish under README/CAPACITY/' +
      (PLATFORM ? PLATFORM + '/' : '') + ' — run measurePlatform.js on an Ubuntu box first.');
    process.exit(1);
  }

  const page = fs.readFileSync(PAGE, 'utf8');
  const a = page.indexOf(OPEN);
  const b = page.indexOf(SHUT);
  if (a === -1 || b === -1 || b < a) {
    console.log('README.md has no capacity:ubuntu-relay block — add the markers first:');
    console.log('  ' + OPEN);
    console.log('  ' + SHUT);
    process.exit(1);
  }

  const built = render(c);
  const next = page.slice(0, a) + built + page.slice(b + SHUT.length);

  if (next === page) {
    console.log('README.md capacity block is current (' +
      String(c.commit || '?').slice(0, 7) + ').');
    return;
  }

  if (process.argv.indexOf('--check') !== -1) {
    console.log('README.md capacity block is OUT OF DATE against ' + PLATFORM +
      ' (' + String(c.commit || '?').slice(0, 7) + '). Run:');
    console.log('  node spirit/test/publishCapacity.js');
    process.exit(1);
  }

  fs.writeFileSync(PAGE, next);
  console.log('README.md capacity block rewritten from ' + PLATFORM +
    ' (' + String(c.commit || '?').slice(0, 7) + ', ' +
    String(c.measuredAt || '?').slice(0, 10) + ').');
  console.log('Stage it by name. Never `git add -A` in this repo.');
}

main();
