'use strict';

// spirit/test/publishCapacity.js
// THE FRONT PAGE'S CAPACITY CLAIM, WRITTEN BY THE MEASUREMENT.
//
//   Andy, 2026-09-23: "the front page README.md should have a marked block
//   that will be auto-updated with the ubuntu-relay capacity only, the rest
//   of the auto-generated capacity branch of the README/ tree can be pushed
//   as is" — and, on why any of this exists: "core improvements WILL move
//   the numbers we document in the README tree of the repo."
//
//   node spirit/test/publishCapacity.js          rewrite the block
//   node spirit/test/publishCapacity.js --check   exit 1 if it is out of date
//
// ── UBUNTU ONLY, AND THAT IS THE WHOLE POINT ─────────────────────────
//
// Andy, the same day: *"swl harness is the target for relay, windows may
// be the prime target for node."* The front page makes ONE claim, about
// the box a relay actually runs on. A Windows run must never touch it —
// not because the Windows figures are worse, but because a front page
// that silently shows whichever platform measured last is a front page
// nobody can cite.
//
// The per-platform detail is not summarised here and is not meant to be.
// It is generated whole by `measurePlatform.js --save` and committed as
// it stands; this block links to it.
//
// ── IT PUBLISHES THE MEASUREMENT'S AGE, NOT JUST ITS NUMBERS ─────────
//
// Every figure carries the commit and date it was taken at. A generated
// block can be stale exactly as a typed one can — `capacityFresh.js`
// caught the 197 that sat on this page for two days — and the difference
// between the two is that this one says how old it is without being
// asked. A reader who can see "measured at 27374ee, 2026-09-21" can
// weigh the number; a reader looking at a bare "197 bytes" cannot.

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..', '..');
const PAGE = path.join(ROOT, 'README.md');
// ── WHICH UBUNTU, AND WHY IT IS NOT NAMED HERE ───────────────────────
//
//   Andy, 2026-09-23: "the index to platforms may have to be updated when
//   i have my pure-ubuntu box live again."
//
// So the slug is CHOSEN, not written down. A bare-metal Ubuntu measurement
// wins over a WSL one the moment it exists, with no edit here and no
// release note — because the day that box comes up is the day this page
// should stop quoting a virtual machine, and nobody will remember to come
// and change a constant.
//
// WSL IS A PROXY AND THE BLOCK SAYS SO. Same distribution, same libc, same
// Node — but a VM on a 64 GB workstation, not a 1 GB VPS under memory
// pressure. It is the best Ubuntu figure available until it is not, and a
// reader deserves to know which one they are looking at.
function pickUbuntu() {
  const dir = path.join(ROOT, 'README', 'CAPACITY');
  let names = [];
  try {
    names = fs.readdirSync(dir).filter(function (nm) {
      return /^ubuntu/i.test(nm) && fs.existsSync(path.join(dir, nm, 'capacity.json'));
    }).sort();
  } catch (e) { names = []; }
  const bare = names.filter(function (nm) { return !/wsl/i.test(nm); });
  return (bare.length ? bare : names)[0] || '';
}

const PLATFORM = pickUbuntu();
const SOURCE = PLATFORM
  ? path.join(ROOT, 'README', 'CAPACITY', PLATFORM, 'capacity.json')
  : '';

const OPEN = '<!-- capacity:ubuntu-relay:start — generated by spirit/test/publishCapacity.js; do not edit by hand -->';
const SHUT = '<!-- capacity:ubuntu-relay:end -->';

function n(x) { return Number(x || 0).toLocaleString('en-US'); }

// `mb()` and `connected()` STOOD HERE and went with the tables. The block
// prints one figure now, so a helper that formats a column has nothing to
// format — and a dead helper is the next reader's wrong turn.

// ── THE CLAIM IS ONE SENTENCE, AND THE DETAIL LIVES ELSEWHERE ───────
//
//   Andy, 2026-09-23: "the top README.md has a capacity claim for a ubuntu
//   relay, in a simple statment: A 1 GB RAM VPS server with 10 GB disc
//   space can hold live connections for <number> members. Details
//   measurements can be found here <link to top of capacity docs per
//   platform>. lot's of boring data on the front page won't help."
//
// So this emits ONE figure a stranger can act on, and a link. The tables
// it replaced were true and unreadable: eleven rows of resident bytes and
// per-connection costs on the page somebody reads to decide whether to
// keep reading.
//
// THE NUMBER IS LIVE CONNECTIONS, NOT ROWS, because after 2026-09-23
// those are the same thing — a relay admits only what it can serve, and
// the seat is held whether the member is online or not. Andy: "RAM cap
// and member cap go lock-step." Publishing a disc-derived roll is what
// put "5.5 million members" on this page, four thousand times the truth.
//
// THE BOX IS THE ONE PEOPLE ACTUALLY RENT: 1 GB of RAM, 10 GB of disc.
// Not the smallest that works — the smallest that is worth quoting.
const VPS_RAM_MB = 1024;
const VPS_DISC_GB = 10;

// What the operating system, Caddy and journald take before the relay
// starts, plus the agreed 25 MB safety margin. THE ONE ASSUMED FIGURE ON
// THE PAGE, and it is stated as one: everything else here is measured. It
// is worth thousands of members either way, so it is deliberately
// generous rather than flattering.
const BOX_OVERHEAD_MB = 150;

// How the figure was arrived at, in the reader's own terms. Silent about
// nothing: a single run is stated as a single run.
function runsNote(c) {
  const runs = Number(c.runs) || 1;
  const sp = c.spread && c.spread.perStreamProcessBytes;
  if (runs < 2) {
    return ' **This is one run**, so the connection figure carries the ' +
      'noise of a single measurement — repeated runs of this tool on one ' +
      'box have differed by over a tenth.';
  }
  return ' The connection figure is the **median of ' + runs + ' runs**' +
    (sp ? ', which spanned ' + n(sp.low) + '–' + n(sp.high) + ' bytes (' +
      sp.spreadPct + '%)' : '') + '.';
}

function render(c) {
  const per = Number(c.perStreamProcessBytes || 0);
  const rest = Number(c.relayAtRestRss || 0) / 1048576;
  const carded = Number(c.perMemberRowBytes || 0);

  const forStreams = VPS_RAM_MB - rest - BOX_OVERHEAD_MB;
  const members = per > 0 ? Math.floor((forStreams * 1048576) / per) : 0;

  // Rounded DOWN to two significant figures. A generated number with four
  // digits invites a precision the assumption above cannot support.
  const rounded = members >= 1000
    ? Math.floor(members / 1000) * 1000
    : Math.floor(members / 100) * 100;

  const rows = carded > 0
    ? Math.floor((VPS_DISC_GB * 1073741824) / carded)
    : 0;

  const lines = [];
  lines.push(OPEN);
  lines.push('');
  lines.push('**A ' + (VPS_RAM_MB / 1024) + ' GB VPS with ' + VPS_DISC_GB +
    ' GB of disc holds live connections for about ' + n(rounded) + ' members.**');
  lines.push('');
  lines.push('Every one of them keeps their seat whether they are online or not — ' +
    'a relay admits only as many members as it can serve at once, so the number ' +
    'above is the membership, not a peak.');
  lines.push('');
  lines.push('Measured on `' + PLATFORM + '` at `' + String(c.commit || '?').slice(0, 7) +
    '`, ' + String(c.measuredAt || '?').slice(0, 10) + ': ' + rest.toFixed(0) +
    ' MB resident at rest, ' + n(per) + ' bytes a held connection' +
    (carded ? ', ' + n(carded) + ' bytes a member on disc' : '') +
    '. Allowing ' + BOX_OVERHEAD_MB + ' MB for the operating system and web server, ' +
    'which is the one estimated figure here.' +
    // ── HOW MANY RUNS, AND HOW MUCH THEY DISAGREED ────────────────
    //
    //   Andy: "publish the median and how many runs it's over AND the
    //   spread.... that's honest."
    //
    // A figure from ONE run says so, rather than looking like a settled
    // number. The page that carried 42,691 bytes a connection was
    // publishing the lowest of three samples that ranged 14% — the most
    // flattering one — on the same page where the overhead allowance is
    // deliberately generous. Two standards, one page.
    runsNote(c) +
    (rows ? ' Disc is nowhere near binding: ' + VPS_DISC_GB + ' GB would store ' +
      (rows / 1000000).toFixed(1) + ' million rows.' : '') +
    (/wsl/i.test(PLATFORM)
      ? ' **Taken under WSL**, which is the same distribution and runtime but a ' +
        'workstation rather than a VPS; bare-metal figures replace these ' +
        'automatically once such a box publishes.'
      : ''));
  lines.push('');
  lines.push('**[All the measurements, both platforms, and the command to re-run them →](README/CAPACITY/)**');
  lines.push('');
  lines.push(SHUT);
  return lines.join('\n');
}

function main() {
  let c = null;
  try { c = JSON.parse(fs.readFileSync(SOURCE, 'utf8')); }
  catch (e) {
    console.log('no Ubuntu measurement to publish under README/CAPACITY/' +
      (PLATFORM ? PLATFORM + '/' : '') + ' — run measurePlatform.js on an Ubuntu box first.');
    process.exit(1);
  }

  const page = fs.readFileSync(PAGE, 'utf8');
  const a = page.indexOf(OPEN);
  const b = page.indexOf(SHUT);
  if (a === -1 || b === -1 || b < a) {
    console.log('README.md has no capacity:ubuntu-relay block — add the markers first:');
    console.log('  ' + OPEN);
    console.log('  ' + SHUT);
    process.exit(1);
  }

  const built = render(c);
  const next = page.slice(0, a) + built + page.slice(b + SHUT.length);

  // ── COMPARED WITHOUT LINE ENDINGS, AND WRITTEN WITH THE FILE'S ────
  //
  // This generator writes LF. Git checks README.md out with CRLF on
  // Windows, so on a FRESH CLONE the comparison below found a difference
  // on every one of 66 lines and `--check` reported the published block
  // as out of date when it was identical.
  //
  // Measured 2026-09-23 in a worktree at d1dd409: `guarantees.js` went
  // red on "the published block and the measurement disagree" for a
  // reason that had nothing to do with either. The guarantee that this
  // repo's published capacity IS its measured capacity was failing for a
  // stranger cloning it — which is the one reader it exists for.
  //
  // Found because wsl-claude asked for the existing suite to be run
  // against the tree before cycle 11 started, and Andy backed the ask. A
  // baseline nobody took is a baseline that hides this.
  const CR = String.fromCharCode(13);
  const NL = String.fromCharCode(10);
  const LF = function (t) { return String(t).split(CR + NL).join(NL); };
  const same = function (x, y) { return LF(x) === LF(y); };

  if (same(next, page)) {
    console.log('README.md capacity block is current (' +
      String(c.commit || '?').slice(0, 7) + ').');
    return;
  }

  if (process.argv.indexOf('--check') !== -1) {
    console.log('README.md capacity block is OUT OF DATE against ' + PLATFORM +
      ' (' + String(c.commit || '?').slice(0, 7) + '). Run:');
    console.log('  node spirit/test/publishCapacity.js');
    process.exit(1);
  }

  // Written back in the convention the file already uses, so a generator
  // run does not turn a whole page into a diff.
  const crlf = (page.split(CR + NL).length - 1) > (page.split(NL).length / 2);
  fs.writeFileSync(PAGE, crlf ? LF(next).split(NL).join(CR + NL) : LF(next));
  console.log('README.md capacity block rewritten from ' + PLATFORM +
    ' (' + String(c.commit || '?').slice(0, 7) + ', ' +
    String(c.measuredAt || '?').slice(0, 10) + ').');
  console.log('Stage it by name. Never `git add -A` in this repo.');
}

main();
