version: '2'
services:
  app:
    container_name: zs4-app
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo
  mongo:
    container_name: zs4-mongo
    image: launcher.gcr.io/google/mongodb3
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
